/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Supplies;

import Employee.E_Scroll;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author AhmedMagedMohamedHas
 */
public class Scrool extends javax.swing.JPanel {

    /**
     * Creates new form Scrool
     */
    private JPanel innerPanel;
    private JScrollPane jScrollPane1;
    public Scrool(ResultSet rs) throws SQLException {
        initComponents();
        jScrollPane1 = new raven.scroll.win11.ScrollPaneWin11();
        innerPanel = new JPanel();
        innerPanel.setLayout(new BoxLayout(innerPanel, BoxLayout.Y_AXIS));
        int cnt=0;
        try {
            while (rs.next()) {
                cnt++;
                String username = rs.getString("Ausername");
                float price = Float.parseFloat(rs.getString("Price"));
                Date date = rs.getDate("OrderDate");
                String s_type = rs.getString("Stype");
                H_Rec r = new H_Rec(username,price,date,s_type);
                r.setPreferredSize(new Dimension(600, 55));  //[587, 56]
                innerPanel.add(r);
                JPanel subPanel = new JPanel();
                subPanel.setPreferredSize(new Dimension(560, 5));
                subPanel.setMaximumSize(new Dimension(560, 5));
                subPanel.setMinimumSize(new Dimension(560, 5));
                subPanel.setBackground(new Color(135,135,135));
                innerPanel.add(subPanel);
            }
        } catch (Exception ex) {
            Logger.getLogger(E_Scroll.class.getName()).log(Level.SEVERE, null, ex);
        }
        innerPanel.setBackground(new Color(255,255,255));
        jScrollPane1.setViewportView(innerPanel);
        jScrollPane1.setPreferredSize(new Dimension(630,300));
        jScrollPane1.setBackground(new Color(255,255,255));
        this.add(jScrollPane1, BorderLayout.CENTER);
        System.out.println(cnt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(580, 284));
        setMinimumSize(new java.awt.Dimension(580, 284));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
