/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Bill;

import MainPanels.CenterPanelChildForm;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author AhmedMagedMohamedHas
 */

public class BillPanel extends CenterPanelChildForm {

    /**
     * Creates new form BillPanel
     */
    private boolean key=false;
    private java.sql.Connection con;
    private String clientId,roomNumber;
    public BillPanel() {
        initComponents();
        ResultSet rs ;
        String sqlqurey = "SELECT * FROM dbo.Room WHERE Status = "+1+" ";
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Hotel;encrypt=true;trustServerCertificate=true","Admin","1234");
            java.sql.PreparedStatement pst = con.prepareStatement(sqlqurey);
            rs = pst.executeQuery();
            while(rs.next()){
                roomNumberCombo.addItem(rs.getString("Room_Number"));
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        key=true;
        roomNumberCombo.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomNumberCombo = new combobox.Combobox();
        jPanel3 = new javax.swing.JPanel();
        scrool1 = new Bill.Scrool();
        clientInfo1 = new services.ClientInfo();

        setBackground(new java.awt.Color(255, 255, 255));

        roomNumberCombo.setLabeText("Select Room");
        roomNumberCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                roomNumberComboItemStateChanged(evt);
            }
        });
        roomNumberCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(scrool1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(scrool1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(roomNumberCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clientInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(clientInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(roomNumberCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roomNumberComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_roomNumberComboItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_roomNumberComboItemStateChanged

    private void roomNumberComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumberComboActionPerformed
        // TODO add your handling code here:
        ResultSet result ;
        if(key){
            String selRoom = (String)roomNumberCombo.getSelectedItem();
            try{
                result = con.prepareStatement("SELECT Client.*, Room.*\n"
                        + "FROM Client\n"
                        + "JOIN Check_In_Out ON Client.ClientID = Check_In_Out.clientID\n"
                        + "JOIN Room ON Check_In_Out.Room_N = Room.Room_Number\n"
                        + "WHERE Room.Room_Number = " + selRoom +"\n"
                        + "ORDER BY Check_In_Out.StartDate DESC").executeQuery();
                while(result.next()){
                    String gen = "Male";
                    if(result.getString("Gender").equals("0"))
                        gen = "Female";
                    this.clientId = result.getString("ClientID");
                    this.roomNumber = result.getString("Room_Number");
                    clientInfo1.setInfo(this.clientId, result.getString("Name"), result.getString("Nationality"), result.getString("Phone"), gen);
                    break;
                }
                System.out.println(clientId);
                scrool1.change(Integer.parseInt(clientId));
            }
            catch(Exception ex){
                System.out.println(ex);
            }
            revalidate();
            
        }
        
        
        
        
    }//GEN-LAST:event_roomNumberComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private services.ClientInfo clientInfo1;
    private javax.swing.JPanel jPanel3;
    private combobox.Combobox roomNumberCombo;
    private Bill.Scrool scrool1;
    // End of variables declaration//GEN-END:variables
}
