/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Bill;

import Employee.E_Scroll;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author AhmedMagedMohamedHas
 */
public class Scrool extends javax.swing.JPanel {

    /**
     * Creates new form Scrool
     */
    ResultSet rs;
    private JPanel innerPanel;
    private JScrollPane jScrollPane1;
    public Scrool() {
        initComponents();
    }
    public void change(int clientid) {
        Scroll.removeAll();
        Scroll.revalidate();
        Scroll.repaint();
        System.out.println("we entered the change funciton");
        Scroll.setPreferredSize(new Dimension(590, 280));
        jScrollPane1 = new raven.scroll.win11.ScrollPaneWin11();
        String sqlqurey;
        sqlqurey = "SELECT askFor.serviceType, askFor.SName, Service.price\n" +
                    "FROM Client\n" +
                    "JOIN askFor ON askFor.ClientID = Client.ClientID\n" +
                    "JOIN Service ON askFor.SName = Service.SName and askFor.serviceType = Service.ServiceType\n" +
                    "WHERE Client.ClientID = "+clientid+";";
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Hotel;encrypt=true;trustServerCertificate=true", "Admin", "1234");
            PreparedStatement pst = con.prepareStatement(sqlqurey);
            rs = pst.executeQuery();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        innerPanel = new JPanel();
        innerPanel.setLayout(new BoxLayout(innerPanel, BoxLayout.Y_AXIS));
        try {
            while (rs.next()) {
                System.out.println("we enterd the next");
                String SName = rs.getString("SName");
                String type = rs.getString("ServiceType");
                float price = rs.getFloat("price");
                Bill.Record r = new Bill.Record(SName+" "+type,Float.toString(price));
                r.setPreferredSize(new Dimension(830, 50));
                innerPanel.add(r);
                JPanel subPanel = new JPanel();
                subPanel.setPreferredSize(new Dimension(460, 55));
                subPanel.setMaximumSize(new Dimension(460, 55));
                subPanel.setMinimumSize(new Dimension(460, 55));
                subPanel.setBackground(new Color(135,135,135));
                innerPanel.add(subPanel);
                System.out.println(SName);
                System.out.println(type);
            }
        } catch (SQLException ex) {
            Logger.getLogger(E_Scroll.class.getName()).log(Level.SEVERE, null, ex);
        }
        innerPanel.setBackground(new Color(255,255,255));
        jScrollPane1.setViewportView(innerPanel);
        Scroll.add(jScrollPane1, BorderLayout.CENTER);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        Scroll = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(490, 324));
        setMinimumSize(new java.awt.Dimension(490, 324));
        setPreferredSize(new java.awt.Dimension(490, 324));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Room Price: ");

        Price.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Price))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ScrollLayout = new javax.swing.GroupLayout(Scroll);
        Scroll.setLayout(ScrollLayout);
        ScrollLayout.setHorizontalGroup(
            ScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ScrollLayout.setVerticalGroup(
            ScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        jLabel2.setText("Service");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Scroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Price;
    private javax.swing.JPanel Scroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
